blogger/blog/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('logout/', views.user_logout, name='logout'),
    path('login/', views.user_login, name='login'),
    path('register/', views.user_sign, name='register'),
    path('profile/edit/', views.edit_profile, name='edit'),
    path('add-blog/', views.add_blog, name='add_blog'),
    path('add-category/', views.Add_cat, name='add_cat'),
]

blogger/blogger/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('blog.urls')),
    path("dashboard/", include('dashboard.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogger/dashboard/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('all-post/', views.all_post, name='all_post'),
    path('my-post/', views.my_post, name='my_post'),
    path('all-categories/', views.all_categories, name='all_categories'),
    path('add-category/', views.add_category, name='add_category'),
    path('edit-category/<int:cat_id>/', views.edit_category, name='edit_category'),
    path('delete/category/<int:cat_id>', views.delete_cat, name='delete_cat'),
    path('category/sets/<int:cat_id>', views.cat_set, name='cat_set'),
    path('post/edit/<int:post_id>', views.edit_post, name='edit_post'),
    path('delete/post/<int:post_id>', views.delete_post, name='delete_post'),
]

blogger/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import signals
from django.db.models.signals import post_save
from django.dispatch import receiver
from ckeditor.fields import RichTextField


STAFF_SELECTOR = (
    ('Pending', 'Pending'),
    ('Approved', 'Approved'),
)
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to='images', default='image/profile.png')
    staff = models.CharField(max_length=20, choices=STAFF_SELECTOR , default='Pending')
    def __str__(self):
        return f"{self.user.username}'s Profile"
    


@receiver(post_save, sender=User)
def createProfile(sender, instance, created, **kwargs):
    if created:
        pro = Profile(user=instance)
        pro.save()

class Category(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='cat_user') 
    name = models.CharField(max_length=200)
    cat_image = models.ImageField(upload_to='cat/img', blank=True)
    create_date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.name
    
class Blog(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    thumbnail_image = models.ImageField(upload_to='blog/img')
    pub_date = models.DateTimeField(auto_now_add=True)
    body = RichTextField()
    def __str__(self):
        return f"{self.title} -- {self.user.username.capitalize()} -- {self.pub_date.year} : {self.pub_date.month} : {self.pub_date.day}"

blogger/dashboard/models.py
from django.db import models

# Create your models here.

blogger/dashboard/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages 
from django.contrib.auth.models import User
from blog.models import Profile, Category, Blog
from .form import CategoryForms
from blog.form import Add_blog, CategoryForm


def dashboard(request):
    user = get_object_or_404(User, id=request.user.id)
    profile = get_object_or_404(Profile, user=user)
    if profile.staff == 'Approved':
        return render(request, 'dashboard.html')
    else:
        messages.success(request, 'Your are not team staff')
        return redirect("index")
    
def all_post(request):
    user = get_object_or_404(User, id=request.user.id)
    profile = get_object_or_404(Profile, user=user)
    if profile.staff == 'Approved':
        all_post = Blog.objects.order_by('-pub_date')
        filter_user = User.objects.filter(profile__staff='Approved')
        if request.method == "GET":
            select = request.GET.get('filter')
            if select != None:
                all_post = Blog.objects.filter(user__username=select).order_by('-pub_date')
            if select == 'All':
                return redirect('all_post')
        return render(request, 'all_post.html', {"all_post" : all_post, 'filter_user' : filter_user, 'select' : select})
    else:
        messages.success(request, 'Your are not team staff')
        return redirect('index')
def my_post(request):
    user = get_object_or_404(User, id=request.user.id)
    profile = get_object_or_404(Profile, user=user)
    if profile.staff == 'Approved':
        my_post = Blog.objects.filter(user=request.user).order_by("-pub_date")
        return render(request, 'my_post.html',{"my_post" : my_post})
    else:
        messages.success(request, 'Your are not team staff')
        return redirect('index')
    
def all_categories(request):
    user = get_object_or_404(User, id=request.user.id)
    profile = get_object_or_404(Profile, user=user)
    if profile.staff == 'Approved':
        categories = Category.objects.order_by('-create_date')
        filter_user = User.objects.filter(profile__staff='Approved')
        if request.method == 'GET':
            select = request.GET.get('filter')
            if select == 'All':
                categories = Category.objects.order_by('-create_date')
            elif select != None:
                categories = Category.objects.filter(user__username=select).order_by('-create_date')
                print(select)
            # elif select == '':
        return render(request, 'all_categories.html', {'categories' : categories, "filter_user" : filter_user, 'select_user' : select})
    else:
        messages.success(request, 'Your are not team staff')
        return redirect('index')
    

def delete_cat(request, cat_id):
    category = get_object_or_404(Category, id=cat_id)
    if request.user.id == category.user.id or request.user.id == 1:
        category.delete()
        return redirect(request.META.get('HTTP_REFERER'))
    else:
        messages.success(request,'That is not you category')
        return redirect('all_categories')
        # return redirect(request.META.get('HTTP_REFERER'))

def add_category(request):
    log_user = get_object_or_404(User, id=request.user.id)
    profile = get_object_or_404(Profile, user=log_user)
    if profile.staff == 'Approved':
        user = User.objects.exclude(id=request.user.id).filter(profile__staff='Approved')
        if request.method == 'POST':
            cat_user = request.POST.get('cat_user')
            form = CategoryForms(request.POST or None, request.FILES or None)
            if form.is_valid():
                post = form.save(commit=False)
                post.user_id = cat_user
                post.save()
                return redirect('all_categories')
        else:
            form = CategoryForms()
        return render(request, 'add_category.html', {'users' : user, 'form' : form})
    else:
        messages.success(request, 'Your are not team staff')
        return redirect('index')
    
def edit_category(request, cat_id):
    log_user = get_object_or_404(User, id=request.user.id)
    profile = get_object_or_404(Profile, user=log_user)
    if profile.staff == 'Approved':
        current_cat = Category.objects.get(id=cat_id)
        user = User.objects.exclude(id=request.user.id).filter(profile__staff='Approved')
        if request.method == 'POST':
            cat_user = request.POST.get('cat_user')
            form = CategoryForm(request.POST or None, request.FILES or None, instance=current_cat)
            if form.is_valid():
                post = form.save(commit=False)
                post.user_id = cat_user
                post.save()
                return redirect('all_categories')
        else:
            form = CategoryForm(instance=current_cat)
        return render(request, 'edit_category.html', {'users' : user, 'form' : form, 'cat' : current_cat})
    else:
        messages.success(request, 'Your are not team staff')
        return redirect('index')

def cat_set(request, cat_id):
    cat = Category.objects.get(id=cat_id)
    post_get = Blog.objects.filter(category__id=cat_id)
    return render(request, 'cat_set.html', {'post' : post_get, "cat" : cat})


def edit_post(request, post_id):
    log_user = get_object_or_404(User, id=request.user.id)
    profile = get_object_or_404(Profile, user=log_user)
    if profile.staff == 'Approved':
        current_cat = Blog.objects.get(id=post_id)
        user = User.objects.exclude(id=request.user.id).filter(profile__staff='Approved')
        if request.method == 'POST':
            post_user = request.POST.get('select_onwer')
            form = Add_blog(request.POST or None, request.FILES or None, instance=current_cat)
            cat_form = CategoryForm(request.POST or None, request.FILES or None)
            if form.is_valid():
                post=form.save(commit=False)
                post.user_id= post_user
                post.save()
                return redirect('all_post')
        else:
            form = Add_blog(instance=current_cat)
            cat_form = CategoryForm(request.POST or None, request.FILES or None)

        return render(request, 'edit_post.html', {'users' : user, 'form' : form, 'cat' : current_cat, 'cat_form' : cat_form})
    else:
        messages.success(request, 'Your are not team staff')
        return redirect('index')
    
def delete_post(request, post_id):
    log_user = get_object_or_404(User, id=request.user.id)
    profile = get_object_or_404(Profile, user=log_user)
    if profile.staff == 'Approved':
        post = Blog.objects.get(id=post_id)
        if request.user.id == post.user.id or request.user.id == 1:
            post.delete()
            return redirect(request.META.get('HTTP_REFERER'))
    else:
        messages.success(request,'That is not you post')
        return redirect('all_post')

blogger/dashboard/templates/add_category.html
{% extends 'dashboard/base.html' %}

{% block title %}Add Category{% endblock title %}
{% block content %}

<form method="post" class="row" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="col-8">
        <div class="mb-3">
            <label for="cat_name" class="form-label">Title</label>
            {{form.name}}
        </div>
        <div class="mb-3">
            <label for="cat_img" class="form-label">Category Image</label>
            {{form.cat_image}}
        </div>
    </div>
    <div class="col">
        <div class="w-100 text-end">
            <button type="submit" class="btn btn-outline-primary mb-2">Publish</button>
        </div>
        <div class="w-100">
            <select name="cat_user" class="form-select" id="user">
                <option value="{{request.user.id}}">{{request.user.username}}</option>
                {% for u in users %}
                <option value="{{u.id}}">{{u.username}}</option>
                {% endfor %}
            </select>
            {{form.user}}
        </div>
    </div>
</form>


{% endblock content %}

blogger/dashboard/templates/all_categories.html
{% extends 'dashboard/base.html' %}

{% block title %}All Categories{% endblock title %}


{% block content %}
<div class="w-100 d-flex align-items-center justify-content-between mb-2">
    <div class="w-25">
        <form method="get" class="d-flex gap-2 align-items-center">
            <select name="filter" id="filter" class="form-select">
                <option value="All">All</option>
                {% for u in filter_user %}
                <option value="{{u}}">{{u|capfirst}}</option>
                {% endfor %}
            </select>
            <button type="submit" class="btn btn-outline-secondary">Filter</button>
        </form>
    </div>
    <a href="{% url 'add_category' %}" class="btn btn-outline-secondary">Add Category</a>
</div>
{% for category in categories %}
<div class="alert alert-warning" role="alert">
    <div class="row">
        <div class="col-auto"><img src="{{category.user.profile.profile_pic.url}}"
                class="rounded-circle object-fit-cover" style="object-position: 0% 0%;" width="40px" height="40px"
                alt=""></div>
        <div class="col">
            <div class="w-100 d-flex">
                <div class="w-75">
                    {% if category.blog_set.count > 0 %}
                    <a class="text-dark text-decoration-none"  href="{% url 'cat_set' category.id %}">(<small>{{category.blog_set.count}}</small>)</a> <strong>{{category.name|capfirst}}</strong> <small>{{category.user.username|capfirst}}</small>
                    {% else %}
                    <strong>{{category.name|capfirst}}</strong> <small>{{category.user.username|capfirst}}</small>
                    {% endif %}
                </div>
                <div class="w-75">
                    <p>{{category.create_date|date:'Y/m/d H:i:s A'}} </p>
                </div>
            </div>
            <hr class="m-0">
            <div class="w-100 row">
                <div class="col-auto form-text"><a class="nav-link" href="{% url 'edit_category' category.id  %}"> Edit</a></div>
                <div class="col-auto form-text">Preview</div>
                {% if request.user.id == 1 %}
                <div class="col-auto form-text "><a class="text-danger nav-link p-0 m-0"
                        href="{% url 'delete_cat' category.id %}">Delete</a></div>
                {% elif request.user.id == category.user.id %}
                <div class="col-auto form-text "><a class="text-danger nav-link p-0 m-0"
                        href="{% url 'delete_cat' category.id %}">Delete</a></div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% empty %}
<div class="w-100 text-center">
    <h1 style="text-transform:capitalize;">
        {{select_user}}'s not have any Post🤷‍♀️🤷‍♀️
    </h1>
</div>
{% endfor %}
{% endblock content %}

blogger/dashboard/templates/all_post.html
{% extends 'dashboard/base.html' %}

{% block title %}All Post{% endblock title %}


{% block content %}

<div class="w-100 d-flex align-items-center justify-content-between mb-2">
    <div class="w-25">
        <form method="get" class="d-flex gap-2 align-items-center">
            <select name="filter" id="filter" class="form-select">
                <option value="All">All</option>
                {% for u in filter_user %}
                <option value="{{u.username}}">{{u}}</option>
                {% endfor %}
            </select>
            <button type="submit" class="btn btn-outline-secondary">Filter</button>
        </form>
    </div>
    <a href="{% url 'add_blog' %}" class="btn btn-outline-secondary">Add Post</a>
</div>

{% for post in all_post %}
<div class="alert alert-warning" role="alert">
    <div class="row">
        <div class="col-auto"><img src="{{post.user.profile.profile_pic.url}}"
                class="rounded-circle object-fit-cover" style="object-position: 0% 0%;" width="40px" height="40px"
                alt=""></div>
        <div class="col">
            <div class="w-100 d-flex">
                <div class="w-75">
                    ({{post.category}})
                    <strong>{{post.title|capfirst}}</strong> 
                    <small> {{post.user.username|capfirst}}</small>
                </div>
                <div class="w-75">
                    <p>{{post.pub_date|date:'Y/m/d H:i:s A'}} </p>
                </div>
            </div>
            <hr class="m-0">
            <div class="w-100 row">
                <div class="col-auto form-text"><a class="text-dark text-decoration-none" href="{% url 'edit_post' post.id %}">Edit</a></div>
                <div class="col-auto form-text">Preview</div>
                <div class="col-auto form-text "><a class="text-danger " style="text-decoration: none;" href="{% url 'delete_post' post.id %}">Delete</a></div>
            </div>
        </div>
    </div>
</div>
{% empty %}
<div class="w-100 text-center">
    <h1 style="text-transform:capitalize;">
        {% if select %}
        {{select}}'s not have any Post🤷‍♀️🤷‍♀️
        {% else %}
        Not Found Any Posts🤷‍♀️🤷‍♀️
        {% endif %}
    </h1>
</div>
{% endfor  %}
{% endblock content %}

blogger/dashboard/templates/cat_set.html
{% extends 'dashboard/base.html' %}

{% block title %}All posts{% endblock title %}


{% block content %}

<h1>{{cat.name}}</h1>
{% for posts in post %}
<div class="alert alert-warning" role="alert">
    <div class="row">
        <div class="col-auto"><img src="{{posts.user.profile.profile_pic.url}}"
                class="rounded-circle object-fit-cover" style="object-position: 0% 0%;" width="40px" height="40px"
                alt=""></div>
        <div class="col">
            <div class="w-100 d-flex">
                <div class="w-75">
                    <strong>{{posts.title|capfirst}}</strong> 
                    <small> {{posts.user.username|capfirst}}</small>
                </div>
                <div class="w-75">
                    <p>{{posts.pub_date|date:'Y/m/d H:i:s A'}} </p>
                </div>
            </div>
            <hr class="m-0">
            <div class="w-100 row">
                <div class="col-auto form-text "><a class="text-dark" style="text-decoration: none;" href="{% url 'edit_post' posts.id %}">Edit</a></div>
                <div class="col-auto form-text">Preview</div>
                <div class="col-auto form-text text-danger"><a class="text-danger" style="text-decoration: none;" href="{% url 'delete_post' posts.id %}">Delete</a></div>
            </div>
        </div>
    </div>
</div>
{% endfor  %}
{% endblock content %}

blogger/dashboard/templates/edit_category.html
{% extends 'dashboard/base.html' %}

{% block title %}{{cat.name}}{% endblock title %}
{% block content %}

<form method="post" class="row" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="col-8">
        <div class="mb-3">
            <label for="cat_name" class="form-label">Title</label>
            {{form.name}}
        </div>
        {% if cat.cat_image %}
        <b>Currently: </b> <a href="{{cat.cat_image.url}}">{{cat.cat_image.url}}</a>
        {% endif %}
        <div class="mb-3">
            <label for="cat_img" class="form-label">Category Image</label>
            {{form.cat_image}}
        </div>
    </div>
    <div class="col">
        <div class="w-100 text-end">
            <button type="submit" class="btn btn-outline-primary mb-2">Publish</button>
        </div>
        <div class="w-100">
            <select name="cat_user" class="form-select" id="user">
                <option value="{{request.user.id}}">{{request.user.username}}</option>
                {% for u in users %}
                <option value="{{u.id}}">{{u.username}}</option>
                {% endfor %}
            </select>
            {{form.user}}
        </div>
    </div>
</form>


{% endblock content %}

blogger/dashboard/templates/edit_post.html
{% extends 'dashboard/base.html' %}

{% block title %}Add Post
{% endblock title %}
{% block content %}
<!-- Modal -->
<div class="modal fade" id="Add-Category" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form action="{% url 'add_cat' %}" method="post">
                {% csrf_token %}
                <div class="modal-body">
                    {{cat_form.as_p}}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Add Categories</button>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="mt-2">
    <form method="post" enctype="multipart/form-data">
        <h1>Add Post</h1>
        {% csrf_token %}
        <div class="row">
            <div class="col-md-5">
                <label for="image">
                    <b>Currently</b>
                    <img src="{{cat.thumbnail_image.url}}" width="100%" style="max-height: 350px;" class="object-fit-cover" alt="">
                </label>
                <div class="my-2">
                    {{form.thumbnail_image}}
                </div>
            </div>
            <div class="col-md-auto border px-3 py-4 rounded">
                <div class="row my-2 align-items-center">
                    <div class="col">
                        {{form.category}}
                    </div>
                    <div class="col-5 d-flex align-items-center justify-content-between">
                        <!-- Button trigger modal -->
                        <button type="button" class="btn btn-primary" data-bs-toggle="modal"
                            data-bs-target="#Add-Category">
                            Add Category
                        </button>
                        <select name="select_onwer" class="w-50 form-select" id="select">
                            <option value="{{request.user.id}}">{{request.user|capfirst}}</option>
                            {% for u in users %}
                            <option value="{{u.id}}">{{u|capfirst}}</option>
                            {% endfor %}
                        </select>
                    
                    </div>
                </div>
                <div class="my-2">
                    {{form.title}}
                </div>
                <div class="my-2">
                    {{form.body}}
                </div>
                {{form.media}}
                <button type="submit" class="btn btn-outline-primary">Publish</button>
            </div>
        </div>
    </form>
</div>

{% endblock content %}

blogger/dashboard/templates/my_post.html
{% extends 'dashboard/base.html' %}

{% block title %}My Post{% endblock title %}


{% block content %}

<div class="w-100 text-end mb-2">
    <a href="{% url 'add_blog' %}" class="btn btn-outline-secondary">Add Post</a>
</div>
{% for post in my_post %}
<div class="alert alert-warning" role="alert">
    <div class="row">
        <div class="col-auto"><img src="{{post.user.profile.profile_pic.url}}"
                class="rounded-circle object-fit-cover" style="object-position: 0% 0%;" width="40px" height="40px"
                alt=""></div>
        <div class="col">
            <div class="w-100 d-flex">
                <div class="w-75">
                    ({{post.category}})
                    <strong>{{post.title|capfirst}}</strong> 
                    <small> {{post.user.username|capfirst}}</small>
                </div>
                <div class="w-75">
                    <p>{{post.pub_date|date:'Y/m/d H:i:s A'}} </p>
                </div>
            </div>
            <hr class="m-0">
            <div class="w-100 row">
                <div class="col-auto form-text"><a class="text-dark text-decoration-none" href="{% url 'edit_post' post.id %}">Edit</a></div>
                <div class="col-auto form-text">Preview</div>
                <div class="col-auto form-text "><a class="text-danger " style="text-decoration: none;" href="{% url 'delete_post' post.id %}">Delete</a></div>
            </div>
        </div>
    </div>
</div>
{% empty %}
<div class="w-100 text-center">
    <h1 style="text-transform:capitalize;">
        {{request.user.username}}'s not have any Post🤷‍♀️🤷‍♀️
    </h1>
</div>
{% endfor  %}
{% endblock content %}